apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp
  labels:
    app: fleetman-app
    release: "0-5"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fleetman-app
      release: "0-5"
  template:
    metadata:
      labels:
        app: fleetman-app
        release: "0-5"
    spec:
      containers:
        - image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
          name: fleetman-webapp0-5
