apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp
spec:
  selector:
    matchLabels:
      app: fleetman-webapp
      release: "0-5"
  replicas: 3
  template:
    metadata:
      labels:
        app: fleetman-webapp
        release: "0-5"
    spec:
      containers:
        - name: fleetman-webapp0-5
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---

apiVersion: v1
kind: Pod
metadata:
name: fleetman-queue
labels:
  app: fleetman-queue
  release: "1"
spec:
containers:
  - name: fleetman-queue
    image: richardchesterwood/k8s-fleetman-queue:release1
