apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue
spec:
  selector:
    matchLabels:
      app: fleetman-queue
  replicas: 1
  template:
    metadata:
      labels:
        app: fleetman-queue
    spec:
      containers:
        - name: fleetman-queue
          image: richardchesterwood/k8s-fleetman-queue:release1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postion-simulator
spec:
  selector:
    matchLabels:
      app: postion-simulator
  replicas: 1
  template:
    metadata:
      labels:
        app: postion-simulator
    spec:
      containers:
        - name: fleetman-queue
          image: richardchesterwood/k8s-fleetman-position-simulator:release1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postion-tracker
spec:
  selector:
    matchLabels:
      app: postion-tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: postion-tracker
    spec:
      containers:
        - name: fleetman-tracker
          image: richardchesterwood/k8s-fleetman-position-tracker:release1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice