apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue
spec:
  selector:
    matchLabels:
      app: fleetman-queue
      release: "1"
  replicas: 1
  template:
    metadata:
      labels:
        app: fleetman-queue
        release: "1"
    spec:
      containers:
        - name: fleetman-queue
          image: richardchesterwood/k8s-fleetman-queue:release1
